
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
      
    ports:
      - 8080:8080   
    depends_on:
      - db  

  db:
    image: nouchka/sqlite3:latest
    restart: always
    volumes:
      - ./code/db :/root/db
    environment:
      - SQLITE3_DB=db.sqlite3      
     
