# Generated by Django 4.0.5 on 2022-08-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0007_alter_item_lot_height_alter_item_lot_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='Продукт')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Код продукта')),
                ('avrg_forecast', models.PositiveIntegerField(verbose_name='Суточный прогноз')),
                ('ingredient', models.CharField(max_length=200, verbose_name='Ингредиент')),
                ('code_ingr', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код ингредиента')),
                ('ratio', models.DecimalField(decimal_places=3, default=1, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Суточная потребность',
                'verbose_name_plural': 'Суточная потребность',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 250 знаков', max_length=250, null=True, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол')),
                ('date', models.DateField(help_text="'2022-08-18", verbose_name='Дата')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Продаж',
                'verbose_name_plural': 'Продажи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SellForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_forecast', models.PositiveIntegerField(verbose_name='Будни')),
                ('weekend_forecast', models.PositiveIntegerField(verbose_name='Выходные')),
                ('avrg_forecast', models.PositiveIntegerField(editable=False, verbose_name='Суточные')),
                ('holiday_forecast', models.PositiveIntegerField(verbose_name='Праздники')),
                ('promotion_forecast', models.PositiveIntegerField(verbose_name='Промо')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.category', verbose_name='Категория')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Прогноз продаж',
                'verbose_name_plural': 'Прогнозы продаж',
                'ordering': ['name'],
            },
        ),
    ]
