# Generated by Django 4.0.5 on 2022-08-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrequirement',
            name='daily_requirement',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Суточная потребность'),
        ),
        migrations.AlterField(
            model_name='dailyrequirement',
            name='ratio',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
