# Generated by Django 4.0.5 on 2022-08-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0002_dailyrequirement_daily_requirement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='SellForecast',
        ),
    ]
