# Generated by Django 4.0.5 on 2022-08-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0003_delete_sales_delete_sellforecast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyRequirement',
        ),
    ]
