# Generated by Django 4.0.5 on 2022-08-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0013_alter_dailyrequirement_options_and_more'),
        ('acore', '0004_delete_dailyrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockForecastDays',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='control.stockitem')),
                ('stock_days', models.DecimalField(decimal_places=0, help_text='Не более 4 знаков', max_digits=4)),
            ],
            options={
                'verbose_name': 'Остаток в днях',
                'verbose_name_plural': 'Остатки в днях',
                'ordering': ['-stock_days'],
            },
            bases=('control.stockitem',),
        ),
    ]
