# Generated by Django 4.0.5 on 2022-08-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockForecastDays',
        ),
    ]
