# Generated by Django 4.0.5 on 2022-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0009_toorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='toorder',
            name='supply_pack',
            field=models.IntegerField(default=1, null=True, verbose_name='Упаковка, ед.'),
        ),
    ]
