# Generated by Django 4.0.5 on 2022-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0010_toorder_supply_pack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toorder',
            options={'ordering': ['name'], 'verbose_name': 'Остаток в днях', 'verbose_name_plural': 'Остатки в днях'},
        ),
        migrations.AddField(
            model_name='toorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
