# Generated by Django 4.0.5 on 2022-10-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0011_alter_toorder_options_toorder_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='toorder',
            name='order_sum',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
