# Generated by Django 4.0.5 on 2022-10-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0012_toorder_order_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToOrder_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('supply_pack', models.IntegerField(default=1, null=True, verbose_name='Упаковка, ед.')),
                ('delivery_time', models.IntegerField(default=5, null=True, verbose_name='Буфер, дней')),
                ('fullstock_days', models.IntegerField(default=0, null=True, verbose_name='Запас, дней')),
                ('daily_requirement', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Суточная потребность')),
                ('to_order', models.IntegerField(verbose_name='Заказать, ед.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('to_orders', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Заказать, руб.')),
                ('order_sum', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'ожидание '), ('decline', 'отклонить'), ('approved', 'одобрено')], help_text='Не более 10 знаков', max_length=10)),
            ],
            options={
                'verbose_name': 'Заказать - 3 дня',
                'verbose_name_plural': 'Заказать - 3 дня',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='toorder',
            options={'ordering': ['name'], 'verbose_name': 'Заказать', 'verbose_name_plural': 'Заказать'},
        ),
    ]
