# Generated by Django 4.0.5 on 2022-10-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0013_toorder_3_alter_toorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='toorder',
            name='supplier',
            field=models.CharField(help_text='Не более 200 знаков', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='toorder_3',
            name='supplier',
            field=models.CharField(help_text='Не более 200 знаков', max_length=200, null=True),
        ),
    ]
