# Generated by Django 4.0.5 on 2022-10-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0015_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(auto_now=True, verbose_name='Дата поставки'),
        ),
    ]
