# Generated by Django 4.0.5 on 2022-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0016_remove_order_delivery_time_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(help_text='Не более 10 знаков', max_length=10),
        ),
    ]
