# Generated by Django 4.0.5 on 2022-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0017_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-supplier', 'name'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказ'},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата поставки'),
        ),
    ]
