# Generated by Django 4.0.5 on 2022-11-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0019_lastorder_orderlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
