# Generated by Django 4.0.5 on 2022-11-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acore', '0020_delete_orderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('order_number', models.CharField(help_text='Не более 10 знаков', max_length=10)),
                ('order', models.IntegerField(verbose_name='Заказ, ед.')),
                ('order_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('supplier', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
                'ordering': ['-order_number', '-supplier'],
            },
        ),
    ]
