# Generated by Django 4.0.5 on 2022-08-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 5 цифр', max_digits=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 5 цифр', max_digits=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, unique=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, unique=True)),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], help_text='Не более 50 знаков', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='register.categoryitem')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, verbose_name='Продукт')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('cooking', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='register.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 4 знаков', max_digits=4, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('address', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Код продукта')),
                ('code_ingr', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код ингредиента')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', help_text='Не более 10 знаков', max_length=10, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('ratio', models.DecimalField(decimal_places=3, default=1, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='register.item')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.product', verbose_name='Рецепт на Продукт')),
            ],
            options={
                'verbose_name': 'Рецепт с ингредиентами',
                'verbose_name_plural': 'Рецепты с ингредиентами',
                'ordering': ['product', 'ingredient'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(through='register.RecipeIngredient', to='register.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='register.supplier'),
        ),
    ]
