# Generated by Django 4.0.5 on 2022-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='slug',
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, unique=True, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], help_text='Не более 50 знаков', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], help_text='Не более 10 знаков', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 4 знаков', max_digits=4, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200),
        ),
    ]
