# Generated by Django 4.0.5 on 2022-08-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_category1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
