# Generated by Django 4.0.5 on 2022-07-23 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_recipeingredient_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Изменен'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', help_text='Не более 10 знаков', max_length=10, null=True),
        ),
    ]
