# Generated by Django 4.0.5 on 2022-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_product_created_date_product_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Изменен'),
        ),
    ]
