# Generated by Django 4.0.5 on 2022-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_delete_category1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='best_befor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='delivery_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='supply_lot',
            field=models.IntegerField(null=True),
        ),
    ]
