# Generated by Django 4.0.5 on 2022-07-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_item_created_date_item_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('шт.', ' шт.'), ('м', 'м'), ('m2', 'м2'), ('m3', 'м3')], help_text='Не более 50 знаков', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('шт.', ' шт.'), ('м', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', help_text='Не более 10 знаков', max_length=10, null=True),
        ),
    ]
