# Generated by Django 4.0.5 on 2022-08-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_item_best_befor_item_delivery_time_item_lot_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lot_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
