# Generated by Django 4.0.5 on 2022-07-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_item_unit_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_ingr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.recipeingredient'),
        ),
    ]
