# Generated by Django 4.0.5 on 2022-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_product_code_ingr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code_ingr',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='code_ingr',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, unique=True, verbose_name='Код ингредиента'),
        ),
    ]
