# Generated by Django 4.0.5 on 2022-08-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_product_avrg_forecast_product_holiday_forecast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_time',
            field=models.IntegerField(null=True, verbose_name='Дней'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_height',
            field=models.FloatField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_length',
            field=models.FloatField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lot_width',
            field=models.FloatField(blank=True, null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supply_lot',
            field=models.IntegerField(null=True, verbose_name='lot'),
        ),
    ]
