# Generated by Django 4.0.5 on 2022-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_product_code_ingr_recipeingredient_code_ingr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='code_ingr',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код ингредиента'),
        ),
    ]
