# Generated by Django 4.0.5 on 2022-09-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_item_available_alter_item_delivery_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lot_height',
            new_name='pack_height',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='lot_length',
            new_name='pack_length',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='lot_weight',
            new_name='pack_weight',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='lot_width',
            new_name='pack_width',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supply_lot',
        ),
        migrations.AddField(
            model_name='item',
            name='supply_pack',
            field=models.IntegerField(null=True, verbose_name='pack'),
        ),
    ]
