# Generated by Django 4.0.5 on 2022-07-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_recipeingredient_code_ingr'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Код продукта'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='register.product'),
        ),
    ]
