# Generated by Django 4.0.5 on 2022-07-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_recipeingredient_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['recipe_name', 'ingredient'], 'verbose_name': 'Рецепт с ингредиентами', 'verbose_name_plural': 'Рецепты с ингредиентами'},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.product', verbose_name='Рецепт на Продукт'),
        ),
    ]
