# Generated by Django 4.0.5 on 2022-09-08 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_item_best_befor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='best_befor',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 8), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='supply_pack',
            field=models.IntegerField(default=1, null=True, verbose_name='Упаковка, ед.'),
        ),
    ]
