# Generated by Django 4.0.5 on 2022-07-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'ordering': ['name'], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
