# Generated by Django 4.0.5 on 2022-08-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_item_unit_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(help_text='Не более 12 знаков', max_length=200, unique=True, verbose_name='Код товара'),
        ),
    ]
