# Generated by Django 4.0.5 on 2022-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ratio',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
