# Generated by Django 4.0.5 on 2022-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_remove_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, unique=True),
        ),
    ]
