# Generated by Django 4.0.5 on 2022-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, unique=True, verbose_name='Код'),
        ),
    ]
