# Generated by Django 4.0.5 on 2022-11-16 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_alter_item_best_befor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Изменен'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='item',
            name='best_befor',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 16), null=True),
        ),
    ]
