# Generated by Django 4.0.5 on 2022-11-17 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_category_created_date_category_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='best_befor',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 17), null=True),
        ),
    ]
