# Generated by Django 4.0.5 on 2022-11-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_alter_item_best_befor'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='avrg_forecast',
            field=models.PositiveIntegerField(default=1, editable=False, null=True, verbose_name='Суточные'),
        ),
    ]
