# Generated by Django 4.0.5 on 2022-11-18 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_recipeingredient_ingredient_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='best_befor',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 18), null=True),
        ),
    ]
