# Generated by Django 4.0.5 on 2022-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpexBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('name', models.CharField(help_text='Не более 200 знаков', max_length=200)),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол.')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб')),
                ('supplier', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('invoice', models.CharField(default='Накладная №     , дата   ', max_length=250, null=True, verbose_name='Накладная')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'X-Закупка',
                'verbose_name_plural': 'X-Закупки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpexCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 5 цифр', max_digits=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'X-Категория продукта',
                'verbose_name_plural': 'X-Категории продуктов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpexCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 5 цифр', max_digits=5, unique=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'X-Категория товара',
                'verbose_name_plural': 'X-Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, unique=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, unique=True)),
                ('category', models.CharField(help_text='Не более 200 знаков', max_length=200)),
                ('supplier', models.CharField(help_text='Не более 200 знаков', max_length=200)),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], help_text='Не более 50 знаков', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'X-Товар',
                'verbose_name_plural': 'X-Товары',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImpexProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Код')),
                ('name', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True, verbose_name='Продукт')),
                ('category', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cooking', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'X-Продукт',
                'verbose_name_plural': 'X-Продукты',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImpexRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 200 знаков', max_length=200)),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Код продукта')),
                ('name_ingr', models.CharField(help_text='Не более 200 знаков', max_length=200)),
                ('code_ingr', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код ингредиента')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', help_text='Не более 10 знаков', max_length=10, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('ratio', models.DecimalField(decimal_places=3, default=1, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'X-Рецепт с ингр',
                'verbose_name_plural': 'X-Рецепты с ингр',
                'ordering': ['name', 'name_ingr'],
            },
        ),
        migrations.CreateModel(
            name='ImpexSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('product', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, null=True)),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('price', models.PositiveIntegerField(default=1, verbose_name='Цена, руб')),
                ('sold', models.PositiveIntegerField(default=1, verbose_name='Sold, руб')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='шт.', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'X-Продажа',
                'verbose_name_plural': 'X-Продажи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpexSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 4 знаков', max_digits=4, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('address', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'X-Поставщик',
                'verbose_name_plural': 'X-Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpexTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('item_name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол.')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб')),
                ('partner', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('invoice', models.CharField(default='Накладная №     , дата   ', max_length=250, null=True, verbose_name='Накладная')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'X-Передача',
                'verbose_name_plural': 'X-Передачи',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='ImpexWasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('item_name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол.')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб')),
                ('approve', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('document', models.CharField(default='Акт №     , дата   ', max_length=250, null=True, verbose_name='Акт')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'X-Списание',
                'verbose_name_plural': 'X-Списания',
                'ordering': ['item_name'],
            },
        ),
    ]
