# Generated by Django 4.0.5 on 2022-08-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impexproduct',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='impexproduct',
            name='ingredient',
        ),
    ]
