# Generated by Django 4.0.5 on 2022-08-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0002_remove_impexproduct_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impexbuyitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='impexbuyitem',
            name='item_supplier',
        ),
    ]
