# Generated by Django 4.0.5 on 2022-08-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0003_remove_impexbuyitem_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impexbuyitem',
            name='updated_date',
        ),
    ]
