# Generated by Django 4.0.5 on 2022-08-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0003_remove_impexsaleproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impexproduct',
            name='avrg_forecast',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Суточные'),
        ),
        migrations.AddField(
            model_name='impexproduct',
            name='holiday_forecast',
            field=models.PositiveIntegerField(null=True, verbose_name='Праздники'),
        ),
        migrations.AddField(
            model_name='impexproduct',
            name='promotion_forecast',
            field=models.PositiveIntegerField(null=True, verbose_name='Промо'),
        ),
        migrations.AddField(
            model_name='impexproduct',
            name='weekday_forecast',
            field=models.PositiveIntegerField(null=True, verbose_name='Будни'),
        ),
        migrations.AddField(
            model_name='impexproduct',
            name='weekend_forecast',
            field=models.PositiveIntegerField(null=True, verbose_name='Выходные'),
        ),
    ]
