# Generated by Django 4.0.5 on 2022-08-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0004_remove_impexbuyitem_updated_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImpexStockItem',
        ),
    ]
