# Generated by Django 4.0.5 on 2022-08-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0004_impexproduct_avrg_forecast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impexitem',
            name='available',
        ),
        migrations.AddField(
            model_name='impexitem',
            name='best_befor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='delivery_time',
            field=models.IntegerField(null=True, verbose_name='Дней'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='lot_height',
            field=models.FloatField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='lot_length',
            field=models.FloatField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='lot_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='lot_width',
            field=models.FloatField(blank=True, null=True, verbose_name='width'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='supply_lot',
            field=models.IntegerField(null=True, verbose_name='lot'),
        ),
    ]
