# Generated by Django 4.0.5 on 2022-08-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0005_delete_impexstockitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impexwasteitem',
            old_name='partner',
            new_name='approve',
        ),
        migrations.RenameField(
            model_name='impexwasteitem',
            old_name='invoice',
            new_name='document',
        ),
    ]
