# Generated by Django 4.0.5 on 2022-08-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0005_remove_impexitem_available_impexitem_best_befor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impexsaleproduct',
            options={'ordering': ['-date'], 'verbose_name': 'X-Продажа', 'verbose_name_plural': 'X-Продажи'},
        ),
        migrations.AddField(
            model_name='impexsaleproduct',
            name='date',
            field=models.DateField(help_text="'2022-08-18", null=True, verbose_name='Дата'),
        ),
    ]
