# Generated by Django 4.0.5 on 2022-08-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0006_rename_partner_impexwasteitem_approve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impextransferitem',
            options={'ordering': ['item_name'], 'verbose_name': 'X-Передача', 'verbose_name_plural': 'X-Передачи'},
        ),
        migrations.AlterModelOptions(
            name='impexwasteitem',
            options={'ordering': ['item_name'], 'verbose_name': 'X-Списание', 'verbose_name_plural': 'X-Списания'},
        ),
        migrations.RenameField(
            model_name='impextransferitem',
            old_name='item',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='impexwasteitem',
            old_name='item',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='impextransferitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='impextransferitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexwasteitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='impexwasteitem',
            name='slug',
        ),
    ]
