# Generated by Django 4.0.5 on 2022-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0006_alter_impexsaleproduct_options_impexsaleproduct_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impexsaleproduct',
            options={'ordering': ['-date', 'name'], 'verbose_name': 'X-Продажа', 'verbose_name_plural': 'X-Продажи'},
        ),
        migrations.AlterField(
            model_name='impexsaleproduct',
            name='sold',
            field=models.PositiveIntegerField(default=1, verbose_name='Sold'),
        ),
    ]
