# Generated by Django 4.0.5 on 2022-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0007_alter_impexsaleproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impexitem',
            name='delivery_time',
            field=models.IntegerField(null=True, verbose_name='Поставка, дней'),
        ),
        migrations.AlterField(
            model_name='impexitem',
            name='lot_height',
            field=models.FloatField(blank=True, null=True, verbose_name='высота lot'),
        ),
        migrations.AlterField(
            model_name='impexitem',
            name='lot_length',
            field=models.FloatField(blank=True, null=True, verbose_name='длина lot'),
        ),
        migrations.AlterField(
            model_name='impexitem',
            name='lot_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='вес lot'),
        ),
        migrations.AlterField(
            model_name='impexitem',
            name='lot_width',
            field=models.FloatField(blank=True, null=True, verbose_name='ширина lot'),
        ),
        migrations.AlterField(
            model_name='impexitem',
            name='supply_lot',
            field=models.IntegerField(null=True, verbose_name='supply_lot'),
        ),
    ]
