# Generated by Django 4.0.5 on 2022-08-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0007_alter_impextransferitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impexrecipeingredient',
            options={'ordering': ['name', 'name_ingr'], 'verbose_name': 'X-Рецепт с ингредиентами', 'verbose_name_plural': 'X-Рецепты с ингредиентами'},
        ),
        migrations.RenameField(
            model_name='impexrecipeingredient',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='impexrecipeingredient',
            old_name='product',
            new_name='name_ingr',
        ),
    ]
