# Generated by Django 4.0.5 on 2022-08-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0008_alter_impexrecipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='code',
            field=models.CharField(help_text='Не более 10 знаков', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='code_ingr',
            field=models.CharField(help_text='Не более 12 знаков', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='name',
            field=models.CharField(help_text='Не более 200 знаков', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='name_ingr',
            field=models.CharField(help_text='Не более 200 знаков', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='ratio',
            field=models.CharField(help_text='Не более 10 знаков', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='unit_cost',
            field=models.CharField(help_text='Не более 10 знаков', max_length=10, null=True),
        ),
    ]
