# Generated by Django 4.0.5 on 2022-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0008_alter_impexitem_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impexitem',
            name='lot_height',
        ),
        migrations.RemoveField(
            model_name='impexitem',
            name='lot_length',
        ),
        migrations.RemoveField(
            model_name='impexitem',
            name='lot_weight',
        ),
        migrations.RemoveField(
            model_name='impexitem',
            name='lot_width',
        ),
        migrations.RemoveField(
            model_name='impexitem',
            name='supply_lot',
        ),
        migrations.AddField(
            model_name='impexitem',
            name='pack_height',
            field=models.FloatField(blank=True, null=True, verbose_name='высота pack'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='pack_length',
            field=models.FloatField(blank=True, null=True, verbose_name='длина pack'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='pack_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='вес pack'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='pack_width',
            field=models.FloatField(blank=True, null=True, verbose_name='ширина pack'),
        ),
        migrations.AddField(
            model_name='impexitem',
            name='supply_pack',
            field=models.IntegerField(null=True, verbose_name='supply_pack'),
        ),
    ]
