# Generated by Django 4.0.5 on 2022-08-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0010_alter_impexrecipeingredient_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='code_ingr',
            field=models.IntegerField(null=True),
        ),
    ]
