# Generated by Django 4.0.5 on 2022-09-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0010_alter_impexitem_best_befor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impexsaleproduct',
            name='code',
            field=models.PositiveIntegerField(default=0, help_text='Не более 12 знаков', null=True, verbose_name='Код'),
        ),
    ]
