# Generated by Django 4.0.5 on 2022-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0011_alter_impexsaleproduct_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impexwasteitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Сумма, руб'),
        ),
        migrations.AlterField(
            model_name='impexwasteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 12 знаков', max_digits=12, verbose_name='Кол.'),
        ),
        migrations.AlterField(
            model_name='impexwasteitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Цена, руб'),
        ),
    ]
