# Generated by Django 4.0.5 on 2022-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0011_alter_impexrecipeingredient_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impexrecipeingredient',
            options={'ordering': ['name', 'name_ingr'], 'verbose_name': 'X-Рецепт с ингр', 'verbose_name_plural': 'X-Рецепты с ингр'},
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Код продукта'),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='code_ingr',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код ингредиента'),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='name',
            field=models.CharField(help_text='Не более 200 знаков', max_length=200),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='name_ingr',
            field=models.CharField(help_text='Не более 200 знаков', max_length=200),
        ),
        migrations.AlterField(
            model_name='impexrecipeingredient',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
