# Generated by Django 4.0.5 on 2022-11-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0012_alter_impexwasteitem_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impexrecipeingredient',
            name='unit_cost',
        ),
    ]
