# Generated by Django 4.0.5 on 2022-08-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0012_alter_impexrecipeingredient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impexbuyitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexcategoryitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexdeliveritem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexorderitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexproduct',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexsaleproduct',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='impexsupplier',
            name='slug',
        ),
    ]
