# Generated by Django 4.0.5 on 2022-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impex', '0013_remove_impexrecipeingredient_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impexsupplier',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 4 знаков', max_digits=8, unique=True),
        ),
    ]
