# Generated by Django 4.0.5 on 2022-08-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('name', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('slug', models.SlugField(max_length=255, verbose_name='Url')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('place', models.CharField(default='store', max_length=100, null=True, verbose_name='Место')),
                ('open', models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('sales', models.DecimalField(decimal_places=3, default=0, help_text='Не более 10 знаков', max_digits=10)),
                ('received', models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('transfer', models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('waste', models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('actual', models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, help_text='Не более 12 знаков', max_digits=12)),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('item', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол.')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб')),
                ('partner', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('invoice', models.CharField(default='Акт №     , дата   ', max_length=250, null=True, verbose_name='Акт')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.item', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('item', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол.')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб')),
                ('partner', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('invoice', models.CharField(default='Накладная №     , дата   ', max_length=250, null=True, verbose_name='Накладная')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.item', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Передача',
                'verbose_name_plural': 'Передачи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, null=True)),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('price', models.PositiveIntegerField(default=1, verbose_name='Цена, руб')),
                ('sold', models.PositiveIntegerField(default=1, verbose_name='Sold, руб')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='шт.', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name_sale', to='register.product')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Не более 10 знаков', max_length=10, unique=True)),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('pending', 'ожидание '), ('decline', 'отклонить'), ('approved', 'одобрено'), ('processing', 'обработка'), ('complete', 'готов')], help_text='Не более 10 знаков', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='register.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.supplier')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='DeliverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Номер заказа')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('order_quantity', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'ожидание '), ('decline', 'отклонить'), ('approved', 'одобрено'), ('processing', 'обработка'), ('complete', 'готов')], help_text='Не более 10 знаков', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_deliver', to='control.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_deliver', to='register.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.supplier')),
            ],
            options={
                'verbose_name': 'На пути',
                'verbose_name_plural': 'На путях',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='BuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('item', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол.')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб')),
                ('item_supplier', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('invoice', models.CharField(default='Накладная №     , дата   ', max_length=250, null=True, verbose_name='Накладная')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.item', verbose_name='Наименование')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.supplier')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'ordering': ['name'],
            },
        ),
    ]
