# Generated by Django 4.0.5 on 2022-08-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveitem',
            name='document',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Заполнил'),
        ),
        migrations.AlterField(
            model_name='moveitem',
            name='place',
            field=models.CharField(default='', help_text='Стеллаж - Ряд - Место', max_length=250, null=True, verbose_name='Место'),
        ),
    ]
