# Generated by Django 4.0.5 on 2022-08-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyitem',
            name='updated_date',
        ),
    ]
