# Generated by Django 4.0.5 on 2022-08-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_remove_buyitem_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteitem',
            old_name='partner',
            new_name='approve',
        ),
        migrations.RenameField(
            model_name='wasteitem',
            old_name='invoice',
            new_name='document',
        ),
    ]
