# Generated by Django 4.0.5 on 2022-07-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('control', '0002_orderitem_unit_alter_saleproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveritem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_deliver', to='register.item'),
        ),
    ]
