# Generated by Django 4.0.5 on 2022-08-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_moveitem_document_alter_moveitem_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moveitem',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Место', 'verbose_name_plural': 'Место'},
        ),
        migrations.AlterField(
            model_name='moveitem',
            name='document',
            field=models.CharField(default='User ', max_length=250, null=True, verbose_name='Заполнил'),
        ),
        migrations.AlterField(
            model_name='moveitem',
            name='place',
            field=models.CharField(default='  ', help_text='Стеллаж - Ряд - Место', max_length=250, null=True, verbose_name='Место'),
        ),
    ]
