# Generated by Django 4.0.5 on 2022-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_deliveritem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveritem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('processing', 'Processing'), ('complete', 'Complete'), ('bulk', 'Bulk')], help_text='Не более 10 знаков', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(help_text='Не более 10 знаков', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('processing', 'Processing'), ('complete', 'Complete'), ('bulk', 'Bulk')], help_text='Не более 10 знаков', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='actual',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Не более 12 знаков', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='move',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='open',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='received',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sales',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='transfer',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='waste',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
    ]
