# Generated by Django 4.0.5 on 2022-08-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_moveitem_options_alter_moveitem_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='daily_requirement',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Суточная потребность'),
        ),
    ]
