# Generated by Django 4.0.5 on 2022-08-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('control', '0003_rename_partner_wasteitem_approve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='  ', help_text='Стеллаж - Ряд - Место', max_length=250, null=True, verbose_name='Акт')),
                ('document', models.CharField(default='Кто(user) внес: ', max_length=250, null=True, verbose_name='Акт')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.item', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Место',
                'ordering': ['name'],
            },
        ),
    ]
