# Generated by Django 4.0.5 on 2022-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_stockitem_daily_requirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyitem',
            options={'ordering': ['-created_date'], 'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки'},
        ),
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'ordering': ['-created_date'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='date',
            field=models.DateField(help_text="'2022-08-18", null=True, verbose_name='Дата'),
        ),
    ]
