# Generated by Django 4.0.5 on 2022-07-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_buyitem_cost_alter_buyitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
