# Generated by Django 4.0.5 on 2022-07-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_remove_orderitem_code_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyitem',
            name='code',
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='gram', help_text='Не более 10 знаков', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
