# Generated by Django 4.0.5 on 2022-08-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_weekdaysale_weekendsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekendSale',
        ),
    ]
