# Generated by Django 4.0.5 on 2022-07-21 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_recipeingredient_unit'),
        ('control', '0007_remove_buyitem_code_alter_buyitem_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_buy', to='register.item', verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Кол.'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='gram', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='unit_cost',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена, руб'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена, руб'),
        ),
    ]
