# Generated by Django 4.0.5 on 2022-08-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_delete_weekendsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, null=True)),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('sold', models.PositiveIntegerField(default=1, verbose_name='Sold, руб')),
                ('first_day', models.DateField()),
                ('last_day', models.DateField()),
            ],
        ),
    ]
