# Generated by Django 4.0.5 on 2022-08-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_weekendsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdaysale',
            name='date',
            field=models.DateField(help_text="'2022-08-18", null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='weekendsale',
            name='date',
            field=models.DateField(help_text="'2022-08-18", null=True, verbose_name='Дата'),
        ),
    ]
