# Generated by Django 4.0.5 on 2022-07-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_remove_saleproduct_unit_alter_saleproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='slug',
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена, руб'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
