# Generated by Django 4.0.5 on 2022-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_weekdaysale_first_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='Продукт')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Код продукта')),
                ('avrg_forecast', models.PositiveIntegerField(verbose_name='Суточный прогноз')),
                ('ingredient', models.CharField(max_length=200, verbose_name='Ингредиент')),
                ('code_ingr', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код ингредиента')),
                ('ratio', models.DecimalField(decimal_places=4, default=1, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('daily_requirement', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Суточная потребность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Суточная потребность',
                'verbose_name_plural': 'Суточная потребность',
                'ordering': ['product'],
            },
        ),
    ]
