# Generated by Django 4.0.5 on 2022-07-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_recipeingredient_unit'),
        ('control', '0011_remove_saleproduct_slug_alter_saleproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='register.item'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
    ]
