# Generated by Django 4.0.5 on 2022-08-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_dailyrequirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrequirement',
            options={'ordering': ['product', 'ingredient'], 'verbose_name': 'Суточная потребность', 'verbose_name_plural': 'Суточная потребность'},
        ),
        migrations.AlterField(
            model_name='dailyrequirement',
            name='avrg_forecast',
            field=models.PositiveIntegerField(null=True, verbose_name='Суточный прогноз'),
        ),
    ]
