# Generated by Django 4.0.5 on 2022-09-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_item_available_alter_item_delivery_time_and_more'),
        ('control', '0013_alter_dailyrequirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='delivery',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Пути'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Пути, руб'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='delivery_time',
            field=models.IntegerField(null=True, verbose_name='Буфер, дней'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='fullstock',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True, verbose_name='Запас, ед.'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='fullstock_days',
            field=models.DecimalField(decimal_places=0, help_text='Не более 4 знаков', max_digits=4, null=True, verbose_name='Запас, дней'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_days',
            field=models.DecimalField(decimal_places=0, help_text='Не более 4 знаков', max_digits=4, null=True, verbose_name='Запас, дней'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Не более 10 знаков', max_length=10, unique=True)),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('order_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'ожидание '), ('decline', 'отклонить'), ('approved', 'одобрено')], help_text='Не более 10 знаков', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='register.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.supplier')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_date', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='DeliverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Номер заказа')),
                ('supplier', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, unique=True)),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('item', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, unique=True)),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('order_quantity', models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'ожидание '), ('decline', 'отклонить'), ('approved', 'одобрено')], help_text='Не более 10 знаков', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_deliver', to='control.orderitem')),
            ],
            options={
                'verbose_name': 'На пути',
                'verbose_name_plural': 'На путях',
                'ordering': ['order_number'],
            },
        ),
    ]
