# Generated by Django 4.0.5 on 2022-07-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_recipeingredient_unit'),
        ('control', '0013_alter_buyitem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.item', verbose_name='Наименование'),
        ),
    ]
