# Generated by Django 4.0.5 on 2022-07-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_alter_buyitem_code_alter_buyitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код'),
        ),
    ]
