# Generated by Django 4.0.5 on 2022-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_alter_stockitem_stock_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='stock_days',
            field=models.DecimalField(decimal_places=0, default=3000, help_text='Не более 4 знаков', max_digits=4, null=True, verbose_name='Остаток, дней'),
        ),
    ]
