# Generated by Django 4.0.5 on 2022-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_alter_saleproduct_code_alter_stockitem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='deliveritem',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='deliveritem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('piece', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
    ]
