# Generated by Django 4.0.5 on 2022-07-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_recipeingredient_unit'),
        ('control', '0016_orderitem_code_saleproduct_slug_alter_buyitem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveritem',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_deliver', to='control.orderitem'),
        ),
        migrations.AlterField(
            model_name='deliveritem',
            name='order_number',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='deliveritem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_deliver', to='register.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(help_text='Не более 10 знаков', max_length=10, unique=True),
        ),
    ]
