# Generated by Django 4.0.5 on 2022-09-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_alter_stockitem_stock_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='daily_requirement',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Суточная потребность'),
        ),
    ]
