# Generated by Django 4.0.5 on 2022-07-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_deliveritem_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
