# Generated by Django 4.0.5 on 2022-07-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_alter_stockitem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('шт.', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='deliveritem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('шт.', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('шт.', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('kg', 'кг'), ('gram', 'г'), ('liter', 'л'), ('шт.', ' шт.'), ('meter', 'м'), ('m2', 'м2'), ('m3', 'м3')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
    ]
