# Generated by Django 4.0.5 on 2022-09-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_alter_stockitem_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='fullstock_days',
            field=models.IntegerField(default=0, null=True, verbose_name='Запас, дней'),
        ),
    ]
