# Generated by Django 4.0.5 on 2022-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_alter_stockitem_fullstock_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='first_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
