# Generated by Django 4.0.5 on 2022-11-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_stockitem_first_cost_stockitem_last_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferitem',
            options={'ordering': ['-id'], 'verbose_name': 'Передача', 'verbose_name_plural': 'Передачи'},
        ),
        migrations.AlterModelOptions(
            name='wasteitem',
            options={'ordering': ['-id', 'name'], 'verbose_name': 'Списание', 'verbose_name_plural': 'Списания'},
        ),
    ]
