# Generated by Django 4.0.5 on 2022-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_alter_buyitem_unit_alter_deliveritem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
