# Generated by Django 4.0.5 on 2022-07-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_orderitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveritem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
