# Generated by Django 4.0.5 on 2022-11-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_alter_transferitem_options_alter_wasteitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyitem',
            options={'ordering': ['-id'], 'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки'},
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='stock_days',
            field=models.DecimalField(decimal_places=0, default=3000, help_text='Не более 4 знаков', max_digits=4, null=True, verbose_name='Остаток в днях'),
        ),
    ]
