# Generated by Django 4.0.5 on 2022-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_deliveritem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveritem',
            name='order_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
