# Generated by Django 4.0.5 on 2022-11-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_alter_buyitem_options_alter_stockitem_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='supplier',
            field=models.CharField(help_text='Не более 200 знаков', max_length=200, null=True, verbose_name='Поставщик'),
        ),
    ]
