# Generated by Django 4.0.5 on 2022-11-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0024_alter_stockitem_daily_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Суточная, руб'),
        ),
    ]
