# Generated by Django 4.0.5 on 2022-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_alter_buyitem_slug_alter_deliveritem_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200),
        ),
    ]
