# Generated by Django 4.0.5 on 2022-08-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_item_unit_alter_recipeingredient_unit'),
        ('control', '0026_alter_stockitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='code',
            field=models.ForeignKey(help_text='Не более 12 знаков', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_code', to='register.item', verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='register.item', verbose_name='Наименование'),
        ),
    ]
