# Generated by Django 4.0.5 on 2022-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_alter_buyitem_code_alter_buyitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='sold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
