# Generated by Django 4.0.5 on 2022-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_remove_saleproduct_quantity_saleproduct_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='unit',
            field=models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='шт.', max_length=10, null=True, verbose_name='Ед.изм.'),
        ),
    ]
