# Generated by Django 4.0.5 on 2022-08-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_saleproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена, руб'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Sold, руб'),
        ),
    ]
