# Generated by Django 4.0.5 on 2022-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_alter_saleproduct_price_alter_saleproduct_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='move',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='place',
            field=models.CharField(default='store', max_length=100, null=True, verbose_name='Место'),
        ),
    ]
