# Generated by Django 4.0.5 on 2022-08-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_remove_recipeingredient_quantity_and_more'),
        ('control', '0032_remove_stockitem_move_stockitem_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='invoice',
            field=models.CharField(default='Накладная №         , дата 202_-__-__', max_length=250, null=True, verbose_name='Накладная'),
        ),
        migrations.AddField(
            model_name='buyitem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.supplier'),
        ),
    ]
