# Generated by Django 4.0.5 on 2022-08-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_item_name'),
        ('control', '0033_buyitem_invoice_buyitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='buyname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.item'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='name',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена, руб'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sold',
            field=models.PositiveIntegerField(default=1, verbose_name='Sold, руб'),
        ),
    ]
