# Generated by Django 4.0.5 on 2022-08-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_item_name'),
        ('control', '0034_buyitem_buyname_alter_buyitem_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyitem',
            name='buyname',
        ),
        migrations.AddField(
            model_name='buyitem',
            name='name_buy',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.item', verbose_name='Наименование'),
        ),
    ]
