# Generated by Django 4.0.5 on 2022-08-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_remove_buyitem_buyname_buyitem_name_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='code',
            field=models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код'),
        ),
    ]
