# Generated by Django 4.0.5 on 2022-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_alter_buyitem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='name_buy',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200),
        ),
    ]
