# Generated by Django 4.0.5 on 2022-08-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_alter_buyitem_name_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyitem',
            old_name='name_buy',
            new_name='item',
        ),
    ]
