# Generated by Django 4.0.5 on 2022-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0038_rename_name_buy_buyitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Изменен'),
        ),
    ]
