# Generated by Django 4.0.5 on 2022-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_buyitem_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол.'),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='unit_cost',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Url'),
        ),
    ]
