# Generated by Django 4.0.5 on 2022-08-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0040_alter_buyitem_quantity_alter_buyitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='item_supplier',
            field=models.CharField(help_text='Не более 200 знаков', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='invoice',
            field=models.CharField(default='Накладная № , дата', max_length=250, null=True, verbose_name='Накладная'),
        ),
    ]
