# Generated by Django 4.0.5 on 2022-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0041_buyitem_item_supplier_alter_buyitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='open',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='received',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='transfer',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='waste',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Не более 10 знаков', max_digits=10, null=True),
        ),
    ]
