# Generated by Django 4.0.5 on 2022-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0042_alter_stockitem_open_alter_stockitem_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='invoice',
            field=models.CharField(default='Накладная №     , дата   ', max_length=250, null=True, verbose_name='Накладная'),
        ),
    ]
