# Generated by Django 4.0.5 on 2022-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0043_alter_buyitem_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='product',
            field=models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200, null=True),
        ),
    ]
