# Generated by Django 4.0.5 on 2022-08-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_item_code'),
        ('control', '0044_saleproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name_sale', to='register.product'),
        ),
    ]
