# Generated by Django 4.0.5 on 2022-08-05 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_item_code'),
        ('control', '0045_alter_saleproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='sales',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Не более 10 знаков', max_digits=10),
        ),
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('item', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол.')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб')),
                ('contragent', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('invoice', models.CharField(default='Акт №     , дата   ', max_length=250, null=True, verbose_name='Акт')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.item', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=0, help_text='Не более 12 знаков', max_digits=12, null=True, verbose_name='Код')),
                ('item', models.CharField(db_index=True, help_text='Не более 200 знаков', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('unit', models.CharField(choices=[(None, 'Выбрать ед.изм.'), ('кг', 'кг'), ('л', 'л'), ('шт.', ' шт.')], default='kg', max_length=10, null=True, verbose_name='Ед.изм.')),
                ('unit_cost', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена, руб')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол.')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, руб')),
                ('contragent', models.CharField(help_text='Не более 200 знаков', max_length=200, null=True)),
                ('invoice', models.CharField(default='Накладная №     , дата   ', max_length=250, null=True, verbose_name='Накладная')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.item', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Передача',
                'verbose_name_plural': 'Передачи',
                'ordering': ['name'],
            },
        ),
    ]
