# Generated by Django 4.0.5 on 2022-08-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0046_alter_stockitem_sales_wasteitem_transferitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferitem',
            old_name='contragent',
            new_name='partner',
        ),
        migrations.RenameField(
            model_name='wasteitem',
            old_name='contragent',
            new_name='partner',
        ),
    ]
